### ISSUE TITLE
tx, wx and text viewer have different menues and behaviour

### ISSUE THREAD

**Issue by fenrog** [fenrog/supersid#14]
It is obvious, that the text viewer does not show graphs. Still it could have a plot option which creates an image and stores it.
wx has a plot option, tk not.
tk has partially differnet save options than text of wx.
tk has NOAA markers, wx has none.

Question:
Is there a real need for the wx viewer? Would it be sufficient to bring all missing features to the tk viewer and to abandon the wx viewer?

[Python GUI programming](https://www.tutorialspoint.com/python/python_gui_programming.htm#:~:text=Tkinter%20Programming,to%20the%20Tk%20GUI%20toolkit.): Tkinter − Tkinter is the Python interface to the Tk GUI toolkit shipped with Python.

**Comment by hreschk** [comment]
What features besides the plot option does wx have that tk does not?  Can fixed amplitude scale be an option?

**Comment by fenrog** [comment]
Comparison between text, tk and wx

text:
- F: save Filtered buffers
- R: save Raw buffers
- E: save Extended raw buffers
- C: list the Config file parameters
- V: Version
- ?: display this menu
- X: eXit (without saving)

tk:
- Ctrl+R: File/Save Raw buffers
- Ctrl+F: File/Save Filtered buffers
- Ctrl+E: File/Save Extended raw Buffers
- Ctrl+S: File/Save filtered as ...
- File/Exit
- Help/About (This includes the version information)
- "Save the figure" button

wx:
- Ctrl+B: File/Save Raw Buffers
- Ctrl+F: File/Save Filtered Buffers
- Ctrl+Q: File/Quit
- Ctrl+p: Plot/Plot
- Help/About (This includes the version information)

Inconsistencies
- text has no option "Save filtered as ..."
- tk has "File/Exit", should be "Ctrl+Q: File/Quit" as Ctrl+Q is kind of a default combination to quit a GUI application.
- text should use "Q: Quit" instead of "X: Exit" to be consistent with the GUI versions.
- tk has no option "Plot/Plot"
- wx keyboard shortcut for "File/Save Raw Buffers" is Ctrl+B, shoudl be Ctrl+R
- wx has no option "Ctrl+E: File/Save Extended raw Buffers"
- wx has no option "Ctrl+S: File/Save filtered as ..."
- wx has no option to save the fft image

**Comment by sberl** [comment]
Looks like all that really needs to be done is to add  a "Plot" menu item to tk.
Then we can drop wx completely.
Then we can work on consistency between tk and text, but that's pretty low priority I think.

**Comment by fenrog** [comment]
- wx is entirely removed
- tk has a lot menue
- text is unchanged

fixed with 3dcbdc95f4d67489888f4e33f71ad295aeb5d368, c33a9472cfb8c16c51fa6749061254085a4b6604, ea97cc0735827e4630a79960c7e88f0439dff5c7
